package test

var SystemsFull = `
	{
	"jsonrpc": "2.0",
	"method": "systems.full",
	"params": {
		"sysid": "X8A8322",
		"dataid": 3478055,
		"data": {
		"local": {
			"sysid": "X8A8322",
			"nmosId": "e6682f75-e09a-4b90-904d-70a66a7fd4c7",
			"name": "MER-XLINK-17",
			"config": true,
			"needReboot": false,
			"cloudXlink": false,
			"cloudRegip": "",
			"cloudRegport": 0,
			"localSysport": 10501,
			"sysST": "2025-02-05 19:58:43 +0000",
			"osST": "2025-02-05 19:58:14 +0000",
			"osR": true,
			"sysVer": "1.7.2.16",
			"sysBeta": true,
			"mVideo": 0,
			"mPoint": false,
			"profile": "2",
			"profileName": "NEP - Germany",
			"changeProfile": "2",
			"configSys": {
			"dnsStatic": false,
			"dnsStaticIp1": "8.8.8.8",
			"dnsStaticIp2": "8.8.4.4",
			"nmos": true,
			"nmosId": "e6682f75-e09a-4b90-904d-70a66a7fd4c7",
			"nmosDomain": "local",
			"nmosUseRegistry": false,
			"nmosRegistryAddress": "10.1.3.11",
			"nmosRegistryVersion": "v1.3",
			"nmosRegistrationPort": 80,
			"nmosNodeLabel": "VideoXLink-%sysId%",
			"nmosNodeDescription": "VideoXLink %sysId%",
			"nmosDeviceTxLabel": "%nodeLabel%/Sender/R%id%",
			"nmosDeviceTxDescription": "%nodeDes% Sender Device %name%",
			"nmosDeviceRxLabel": "%nodeLabel%/Receiver/S%id%",
			"nmosDeviceRxDescription": "%nodeDes% Receiver Device %name%",
			"nmosVideoTxLabel": "%nodeLabel%/Sender/R%id%-V",
			"nmosVideoTxDescription": "%nodeDes% Video Sender %name%",
			"nmosVideoRxLabel": "%nodeLabel%/Receiver/S%id%-V",
			"nmosVideoRxDescription": "%nodeDes% Video Receiver %name%",
			"nmosAudioTxLabel": "%nodeLabel%/Sender/R%id%-A",
			"nmosAudioTxDescription": "%nodeDes% Audio Sender %name%",
			"nmosAudioRxLabel": "%nodeLabel%/Receiver/S%id%-A",
			"nmosAudioRxDescription": "%nodeDes% Audio Receiver %name%",
			"ptp": true,
			"ptpLogAnnounceInterval": -2,
			"ptpSyncReceiptTimeout": 3,
			"ptpDomainNumber": 99,
			"ptpEth": "eth6",
			"ptpDscp": 46,
			"ptpPriority1": 128,
			"ptpPriority2": 127,
			"ptpAnnounceReceiptTimeout": 3,
			"ptpLogSyncInterval": -3,
			"ptpLogMinDelayReqInterval": -3,
			"ptpHybrid_e2e": false
			},
			"profiles": [
			{
				"id": "1",
				"profileId": "X8A832285f990",
				"profileName": "New1",
				"genId": "",
				"useCloud": true,
				"valid": 1,
				"validTo": "2023-05-19 14:54:16 +0000",
				"created": "2023-05-19 14:54:16 +0000"
			},
			{
				"id": "2",
				"profileId": "X4A2974dcfba8",
				"profileName": "NEP - Germany",
				"genId": "X2A7393",
				"useCloud": true,
				"valid": 1,
				"validTo": "2023-05-19 14:57:06 +0000",
				"created": "2023-05-19 14:57:06 +0000"
			}
			],
			"adminProxyOn": true,
			"adminProxy": [
			{ "id": "1", "peer": "" },
			{ "id": "2", "peer": "" },
			{ "id": "3", "peer": "" },
			{ "id": "4", "peer": "" }
			],
			"ports": { "sysPort": 10501, "sysOn": true, "portsOn": true, "portsFrom": 10502, "portsTo": 10539 },
			"dnsInUse": "8.8.8.8, 8.8.4.4",
			"enc": [
			{
				"id": "X8A8322-E1",
				"type": 1,
				"enabled": true,
				"name": "Encoder 81",
				"nmosId": "fe05d86e-ece0-4da6-9e2b-f7167561533e",
				"st2110": true,
				"config": true,
				"values": {
				"vIn": "No Signal",
				"aIn": "No Signal",
				"vModeName": "1080i50",
				"vModeBName": "Auto",
				"vCard": "12",
				"vCardConn": "sdi",
				"vTBR": 25.0,
				"vCRFOn": true,
				"vFEC": 1,
				"vCodec": 1,
				"aNmosId": "f6ad572f-0bec-4926-84c8-98805cd57180",
				"a2110NetPri": "eth6",
				"a2110NetPriEnabled": false,
				"a2110NetPriPort": 5002,
				"a2110NetPriIp": "0.0.0.0",
				"vNmosId": "1ac7f5a4-2ead-4f42-8a93-dce1dfedd9e1",
				"v2110NetPri": "eth6",
				"v2110NetPriEnabled": true,
				"v2110NetPriPort": 5000,
				"v2110NetPriIp": "232.1.1.1",
				"ndiSource": "",
				"ndiSourceName": "",
				"ndiSourceCon": false,
				"mPointSender": "none",
				"xLink": true,
				"xLinkp2p": true,
				"running": false,
				"startT": "2000-01-01 00:00:00 +0000"
				},
				"receiver": {
				"id": "X8A3908-D4",
				"sysName": "CER-XLINK-3",
				"name": "CP3.Spare",
				"nmosId": "a9e8ea7c-6048-4785-9568-71a012b8a314",
				"st2110": false,
				"config": true,
				"values": {
					"vIn": "No Signal",
					"aIn": "No Signal",
					"vOut": "No Signal",
					"aOut": "No Signal",
					"aInCh": "0",
					"aInkHz": "0",
					"vCard": "4",
					"vCardConn": "sdi",
					"vModeName": "Auto sense",
					"vBnoInOn": true,
					"vBnoIn": 60,
					"vBufferOn": false,
					"vBuffer": 1,
					"vFRCOn": true,
					"aNmosId": "fb614d8a-9c7e-4e6b-b43f-cbdb95b9ca03",
					"a2110NetPri": "none",
					"a2110NetPriEnabled": false,
					"a2110NetPriPort": 0,
					"a2110NetPriIp": "0.0.0.0",
					"vNmosId": "05407fd3-862e-4c3f-a1dc-a8190a4f1d39",
					"v2110NetPri": "none",
					"v2110NetPriEnabled": false,
					"v2110NetPriPort": 0,
					"v2110NetPriIp": "0.0.0.0",
					"vRef": false,
					"avSync": false,
					"avUnSync": 0,
					"aSync": null,
					"connected": true,
					"xLink": true,
					"xLinkp2p": true,
					"onLocalNet": false,
					"running": true,
					"startT": "2025-01-27 12:28:56 +0000",
					"vFinBuffer": 0
				}
				}
			},
			{
				"id": "X8A8322-E2",
				"type": 1,
				"enabled": true,
				"name": "Encoder 82",
				"nmosId": "a2937b75-59fa-4b9b-8ca1-a815669dbef8",
				"st2110": true,
				"config": true,
				"values": {
				"vIn": "No Signal",
				"aIn": "No Signal",
				"vModeName": "1080i50",
				"vModeBName": "Auto",
				"vCard": "12",
				"vCardConn": "sdi",
				"vTBR": 25.0,
				"vCRFOn": true,
				"vFEC": 1,
				"vCodec": 1,
				"aNmosId": "009115a8-eaae-45f5-b976-c410d7e63d1b",
				"a2110NetPri": "eth6",
				"a2110NetPriEnabled": false,
				"a2110NetPriPort": 5002,
				"a2110NetPriIp": "0.0.0.0",
				"vNmosId": "47d9d3d8-d6c7-4546-8828-873f459b1302",
				"v2110NetPri": "eth6",
				"v2110NetPriEnabled": true,
				"v2110NetPriPort": 5000,
				"v2110NetPriIp": "232.2.2.2",
				"ndiSource": "",
				"ndiSourceName": "",
				"ndiSourceCon": false,
				"mPointSender": "none",
				"xLink": true,
				"xLinkp2p": true,
				"running": false,
				"startT": "2000-01-01 00:00:00 +0000"
				},
				"receiver": {
				"id": "X8A3908-D5",
				"sysName": "CER-XLINK-3",
				"name": "CER.SF.A21",
				"nmosId": "99ea3881-202a-4d11-bc48-64be1c6da611",
				"st2110": false,
				"config": true,
				"values": {
					"vIn": "No Signal",
					"aIn": "No Signal",
					"vOut": "No Signal",
					"aOut": "No Signal",
					"aInCh": "0",
					"aInkHz": "0",
					"vCard": "5",
					"vCardConn": "sdi",
					"vModeName": "Auto sense",
					"vBnoInOn": true,
					"vBnoIn": 60,
					"vBufferOn": false,
					"vBuffer": 1,
					"vFRCOn": true,
					"aNmosId": "9ad9f367-d566-41d8-8ffc-ee278a63a773",
					"a2110NetPri": "none",
					"a2110NetPriEnabled": false,
					"a2110NetPriPort": 0,
					"a2110NetPriIp": "0.0.0.0",
					"vNmosId": "3f32ebdc-16c6-4dc2-b8db-475c497aed75",
					"v2110NetPri": "none",
					"v2110NetPriEnabled": false,
					"v2110NetPriPort": 0,
					"v2110NetPriIp": "0.0.0.0",
					"vRef": false,
					"avSync": false,
					"avUnSync": 0,
					"aSync": null,
					"connected": true,
					"xLink": true,
					"xLinkp2p": true,
					"onLocalNet": false,
					"running": true,
					"startT": "2025-01-27 12:28:47 +0000",
					"vFinBuffer": 0
				}
				}
			}
			],
			"dec": [
			{
				"id": "X8A8322-D1",
				"type": 2,
				"enabled": true,
				"name": "DEC81-VK6 LDX1 | MAIN",
				"nmosId": "d4737ba3-024c-44cd-b080-040f520177f0",
				"st2110": true,
				"config": true,
				"values": {
				"vIn": "1080i50",
				"aIn": "8 Ch 48 kHz",
				"vOut": "1080i50",
				"aOut": "8 Ch 48 kHz",
				"aInCh": "8",
				"aInkHz": "48",
				"vCard": "12",
				"vCardConn": "sdi",
				"vModeName": "Auto",
				"vBnoInOn": true,
				"vBnoIn": 60,
				"vBufferOn": false,
				"vBuffer": 1,
				"aNmosId": "1a6a292a-e0d2-4cfa-9fbc-7dc76c77a708",
				"a2110NetPri": "eth6",
				"a2110NetPriEnabled": true,
				"a2110NetPriPort": 5004,
				"a2110NetPriIp": "232.160.59.129",
				"vNmosId": "65e9fa0b-3662-451f-a851-4836bc666424",
				"v2110NetPri": "eth6",
				"v2110NetPriEnabled": true,
				"v2110NetPriPort": 30000,
				"v2110NetPriIp": "232.160.59.1",
				"vRef": false,
				"vFRCOn": true,
				"avSync": true,
				"avUnSync": 0,
				"xLink": true,
				"xLinkp2p": true,
				"running": true,
				"startT": "2025-03-27 13:23:42 +0000",
				"vFinBuffer": 0
				},
				"sender": {
				"id": "X8A5526-E1",
				"sysName": "VenueKit6 1",
				"name": "TX1 | LDX 1 | MAIN",
				"nmosId": "af261a84-351e-481e-a81c-565658e4e363",
				"st2110": true,
				"values": {
					"vIn": "1080i50",
					"aIn": "8 Ch 48 kHz",
					"vModeName": "1080i50",
					"vModeBName": "Auto",
					"vCard": "12",
					"vCardConn": "sdi",
					"vTBR": 25.0,
					"vCRFOn": true,
					"vFEC": 1,
					"vCodec": 1,
					"aNmosId": "f21bcf12-9dcf-4d93-a6c2-56dee1ad9358",
					"a2110NetPri": "eth7",
					"a2110NetPriEnabled": true,
					"a2110NetPriPort": 5004,
					"a2110NetPriIp": "239.183.22.135",
					"vNmosId": "4e2f4de5-a861-408d-a7bb-1e501e57ca14",
					"v2110NetPri": "eth7",
					"v2110NetPriEnabled": true,
					"v2110NetPriPort": 30000,
					"v2110NetPriIp": "232.183.2.2",
					"ndiSource": "",
					"ndiSourceName": "",
					"ndiSourceCon": false,
					"mPointSender": "none",
					"connected": true,
					"xLink": true,
					"xLinkp2p": true,
					"onLocalNet": false,
					"running": true,
					"startT": "2025-03-27 13:25:31 +0000"
				}
				}
			},
			{
				"id": "X8A8322-D2",
				"type": 2,
				"enabled": true,
				"name": "DEC82-VK6 LDX3 | 16CH MAIN_BU",
				"nmosId": "54ab8bd1-4b4f-48d5-9c26-3d58d868a369",
				"st2110": true,
				"config": true,
				"values": {
				"vIn": "No Signal",
				"aIn": "16 Ch 48 kHz",
				"vOut": "No Signal",
				"aOut": "16 Ch 48 kHz",
				"aInCh": "16",
				"aInkHz": "48",
				"vCard": "12",
				"vCardConn": "sdi",
				"vModeName": "Auto",
				"vBnoInOn": true,
				"vBnoIn": 60,
				"vBufferOn": false,
				"vBuffer": 1,
				"aNmosId": "a97bf259-923f-46b8-a0d1-7da9fe24cb76",
				"a2110NetPri": "eth6",
				"a2110NetPriEnabled": true,
				"a2110NetPriPort": 5004,
				"a2110NetPriIp": "232.160.59.130",
				"vNmosId": "c21c96e5-8494-4e46-9959-afb27b5ee86d",
				"v2110NetPri": "eth6",
				"v2110NetPriEnabled": true,
				"v2110NetPriPort": 30000,
				"v2110NetPriIp": "232.160.59.2",
				"vRef": false,
				"vFRCOn": true,
				"avSync": false,
				"avUnSync": 0,
				"xLink": true,
				"xLinkp2p": true,
				"running": true,
				"startT": "2025-03-27 13:25:38 +0000",
				"vFinBuffer": 0
				},
				"sender": {
				"id": "X8A5526-E2",
				"sysName": "VenueKit6 1",
				"name": "TX2 | LDX 3 | 16CH MAIN_BU",
				"nmosId": "4b073944-1836-4bbe-87bd-d3deb9f1d629",
				"st2110": true,
				"values": {
					"vIn": "No Signal",
					"aIn": "16 Ch 48 kHz",
					"vModeName": "1080i50",
					"vModeBName": "Auto",
					"vCard": "12",
					"vCardConn": "sdi",
					"vTBR": 25.0,
					"vCRFOn": true,
					"vFEC": 1,
					"vCodec": 1,
					"aNmosId": "471549b4-6359-4c78-b424-b357dc73365f",
					"a2110NetPri": "eth7",
					"a2110NetPriEnabled": true,
					"a2110NetPriPort": 5004,
					"a2110NetPriIp": "239.183.234.136",
					"vNmosId": "67066168-619c-4fdb-8170-93cd75cbf60a",
					"v2110NetPri": "eth7",
					"v2110NetPriEnabled": true,
					"v2110NetPriPort": 30000,
					"v2110NetPriIp": "232.183.4.2",
					"ndiSource": "",
					"ndiSourceName": "",
					"ndiSourceCon": false,
					"mPointSender": "none",
					"connected": true,
					"xLink": true,
					"xLinkp2p": true,
					"onLocalNet": false,
					"running": true,
					"startT": "2025-03-27 13:25:34 +0000"
				}
				}
			}
			],
			"ndi": [],
			"srt": [],
			"ndifind": [],
			"l2s": [],
			"network": {
			"nets": [
				{
				"id": "eth0",
				"type": 1,
				"mac": "3C:EC:EF:BE:95:5C",
				"ip": "10.199.128.63",
				"gate": "10.199.128.1",
				"mask": "255.255.255.0",
				"ip_mask": "10.199.128.63/24",
				"dns1": "8.8.8.8",
				"dns2": "8.8.4.4",
				"dnsInUse1": "8.8.8.8",
				"dnsInUse2": "8.8.4.4",
				"dhcp": false,
				"link": true,
				"speed": "1Gbps",
				"system": true,
				"chipOK": true,
				"internet": false,
				"gatePing": true,
				"l2s": false,
				"l2sId": "none",
				"l2sName": "",
				"admin": true,
				"adminOnly": true,
				"igmp": false,
				"enabled": true,
				"defaultLan": false,
				"ndi": false,
				"default": false,
				"backup": false,
				"active": false,
				"allowed": true,
				"response": true,
				"wifiAllowed": false,
				"wifiConnect": false,
				"wifiConnected": false,
				"wifiFastRoaming": false,
				"wifiAp": false,
				"wifiApRunning": false,
				"wifiSSID": "",
				"wifiPSK": "",
				"wifiRSSI": 0,
				"linkTime": "2025-02-05 19:58:50 +0000"
				},
				{
				"id": "eth1",
				"type": 1,
				"mac": "3C:EC:EF:BE:95:5D",
				"ip": "10.98.1.210",
				"gate": "10.98.1.193",
				"mask": "255.255.255.192",
				"ip_mask": "10.98.1.210/26",
				"dns1": "8.8.8.8",
				"dns2": "8.8.4.4",
				"dnsInUse1": "8.8.8.8",
				"dnsInUse2": "8.8.4.4",
				"dhcp": false,
				"link": true,
				"speed": "1Gbps",
				"system": true,
				"chipOK": true,
				"internet": false,
				"gatePing": true,
				"l2s": false,
				"l2sId": "none",
				"l2sName": "",
				"admin": false,
				"adminOnly": false,
				"igmp": false,
				"enabled": true,
				"defaultLan": false,
				"ndi": false,
				"default": true,
				"backup": false,
				"active": true,
				"allowed": true,
				"response": true,
				"wifiAllowed": false,
				"wifiConnect": false,
				"wifiConnected": false,
				"wifiFastRoaming": false,
				"wifiAp": false,
				"wifiApRunning": false,
				"wifiSSID": "",
				"wifiPSK": "",
				"wifiRSSI": 0,
				"linkTime": "2025-02-05 19:58:46 +0000"
				},
				{
				"id": "eth2",
				"type": 1,
				"mac": "3C:EC:EF:BE:95:5E",
				"ip": "10.98.1.146",
				"gate": "10.98.1.129",
				"mask": "255.255.255.192",
				"ip_mask": "10.98.1.146/26",
				"dns1": "8.8.8.8",
				"dns2": "8.8.4.4",
				"dnsInUse1": "8.8.8.8",
				"dnsInUse2": "8.8.4.4",
				"dhcp": false,
				"link": true,
				"speed": "1Gbps",
				"system": true,
				"chipOK": true,
				"internet": false,
				"gatePing": true,
				"l2s": false,
				"l2sId": "none",
				"l2sName": "",
				"admin": false,
				"adminOnly": false,
				"igmp": false,
				"enabled": true,
				"defaultLan": false,
				"ndi": false,
				"default": false,
				"backup": true,
				"active": false,
				"allowed": true,
				"response": true,
				"wifiAllowed": false,
				"wifiConnect": false,
				"wifiConnected": false,
				"wifiFastRoaming": false,
				"wifiAp": false,
				"wifiApRunning": false,
				"wifiSSID": "",
				"wifiPSK": "",
				"wifiRSSI": 0,
				"linkTime": "2025-02-24 14:33:25 +0000"
				},
				{
				"id": "eth3",
				"type": 1,
				"mac": "3C:EC:EF:BE:95:5F",
				"ip": "0.0.0.0",
				"gate": "0.0.0.0",
				"mask": "0.0.0.0",
				"ip_mask": "0.0.0.0/0",
				"dns1": "0.0.0.0",
				"dns2": "0.0.0.0",
				"dnsInUse1": "0.0.0.0",
				"dnsInUse2": "0.0.0.0",
				"dhcp": true,
				"link": false,
				"speed": "?",
				"system": true,
				"chipOK": true,
				"internet": false,
				"gatePing": false,
				"l2s": false,
				"l2sId": "none",
				"l2sName": "",
				"admin": false,
				"adminOnly": false,
				"igmp": false,
				"enabled": false,
				"defaultLan": false,
				"ndi": false,
				"default": false,
				"backup": false,
				"active": false,
				"allowed": true,
				"response": true,
				"wifiAllowed": false,
				"wifiConnect": false,
				"wifiConnected": false,
				"wifiFastRoaming": false,
				"wifiAp": false,
				"wifiApRunning": false,
				"wifiSSID": "",
				"wifiPSK": "",
				"wifiRSSI": 0,
				"linkTime": ""
				},
				{
				"id": "eth4",
				"type": 1,
				"mac": "3C:EC:EF:C0:2B:9A",
				"ip": "10.199.160.59",
				"gate": "10.199.160.58",
				"mask": "255.255.255.254",
				"ip_mask": "10.199.160.59/31",
				"dns1": "8.8.8.8",
				"dns2": "8.8.4.4",
				"dnsInUse1": "0.0.0.0",
				"dnsInUse2": "0.0.0.0",
				"dhcp": false,
				"link": false,
				"speed": "?",
				"system": true,
				"chipOK": true,
				"internet": false,
				"gatePing": false,
				"l2s": false,
				"l2sId": "none",
				"l2sName": "",
				"admin": false,
				"adminOnly": false,
				"igmp": false,
				"enabled": false,
				"defaultLan": false,
				"ndi": false,
				"default": false,
				"backup": false,
				"active": false,
				"allowed": true,
				"response": true,
				"wifiAllowed": false,
				"wifiConnect": false,
				"wifiConnected": false,
				"wifiFastRoaming": false,
				"wifiAp": false,
				"wifiApRunning": false,
				"wifiSSID": "",
				"wifiPSK": "",
				"wifiRSSI": 0,
				"linkTime": ""
				},
				{
				"id": "eth5",
				"type": 1,
				"mac": "3C:EC:EF:C0:2B:9B",
				"ip": "0.0.0.0",
				"gate": "0.0.0.0",
				"mask": "0.0.0.0",
				"ip_mask": "0.0.0.0/0",
				"dns1": "0.0.0.0",
				"dns2": "0.0.0.0",
				"dnsInUse1": "0.0.0.0",
				"dnsInUse2": "0.0.0.0",
				"dhcp": true,
				"link": false,
				"speed": "?",
				"system": true,
				"chipOK": true,
				"internet": false,
				"gatePing": false,
				"l2s": false,
				"l2sId": "none",
				"l2sName": "",
				"admin": false,
				"adminOnly": false,
				"igmp": false,
				"enabled": false,
				"defaultLan": false,
				"ndi": false,
				"default": false,
				"backup": false,
				"active": false,
				"allowed": true,
				"response": true,
				"wifiAllowed": false,
				"wifiConnect": false,
				"wifiConnected": false,
				"wifiFastRoaming": false,
				"wifiAp": false,
				"wifiApRunning": false,
				"wifiSSID": "",
				"wifiPSK": "",
				"wifiRSSI": 0,
				"linkTime": ""
				},
				{
				"id": "eth6",
				"type": 1,
				"mac": "08:C0:EB:36:E4:49",
				"ip": "10.199.160.59",
				"gate": "10.199.160.58",
				"mask": "255.255.255.254",
				"ip_mask": "10.199.160.59/31",
				"dns1": "8.8.8.8",
				"dns2": "8.8.4.4",
				"dnsInUse1": "8.8.8.8",
				"dnsInUse2": "8.8.4.4",
				"dhcp": false,
				"link": true,
				"speed": "25Gbps",
				"system": true,
				"chipOK": true,
				"internet": true,
				"gatePing": true,
				"l2s": false,
				"l2sId": "none",
				"l2sName": "",
				"admin": false,
				"adminOnly": false,
				"igmp": true,
				"enabled": true,
				"defaultLan": true,
				"ndi": false,
				"default": false,
				"backup": false,
				"active": false,
				"allowed": true,
				"response": true,
				"wifiAllowed": false,
				"wifiConnect": false,
				"wifiConnected": false,
				"wifiFastRoaming": false,
				"wifiAp": false,
				"wifiApRunning": false,
				"wifiSSID": "",
				"wifiPSK": "",
				"wifiRSSI": 0,
				"linkTime": "2025-02-05 19:58:44 +0000"
				},
				{
				"id": "eth7",
				"type": 1,
				"mac": "08:C0:EB:36:E4:48",
				"ip": "0.0.0.0",
				"gate": "0.0.0.0",
				"mask": "0.0.0.0",
				"ip_mask": "0.0.0.0/0",
				"dns1": "0.0.0.0",
				"dns2": "0.0.0.0",
				"dnsInUse1": "0.0.0.0",
				"dnsInUse2": "0.0.0.0",
				"dhcp": true,
				"link": false,
				"speed": "?",
				"system": true,
				"chipOK": true,
				"internet": false,
				"gatePing": false,
				"l2s": false,
				"l2sId": "none",
				"l2sName": "",
				"admin": false,
				"adminOnly": false,
				"igmp": false,
				"enabled": false,
				"defaultLan": false,
				"ndi": false,
				"default": false,
				"backup": false,
				"active": false,
				"allowed": true,
				"response": true,
				"wifiAllowed": false,
				"wifiConnect": false,
				"wifiConnected": false,
				"wifiFastRoaming": false,
				"wifiAp": false,
				"wifiApRunning": false,
				"wifiSSID": "",
				"wifiPSK": "",
				"wifiRSSI": 0,
				"linkTime": ""
				}
			],
			"ap": {},
			"modem": { "profiles": [], "simCards": [] }
			},
			"xlinkPeers": []
		},
		"remote": [
			{
			"sysid": "X8A8049",
			"name": "VenueKit6 2",
			"config": true,
			"connected": true,
			"conIp": "10.35.1.252",
			"conPort": 10501,
			"connectedT": "2025-03-27 13:22:51 +0000",
			"xLinkp2p": true,
			"onLocalNet": false,
			"lastSeenT": "2025-03-27 15:50:36 +0000",
			"shutdown": false,
			"shutdownT": "2000-01-01 00:00:00 +0000",
			"reboot": false,
			"rebootT": "2000-01-01 00:00:00 +0000",
			"mVideo": 0,
			"mPoint": false,
			"sysVer": "1.7.2.13",
			"ports": { "sysPort": 10501, "sysOn": true, "portsOn": true, "portsFrom": 10502, "portsTo": 10539 },
			"configSys": {
				"nmos": true,
				"nmosId": "499a39b1-7d9d-485e-a16b-2a297f1019ed",
				"nmosDomain": "local",
				"nmosUseRegistry": false,
				"nmosRegistryAddress": "10.1.3.11",
				"nmosRegistryVersion": "v1.3",
				"nmosRegistrationPort": 80,
				"nmosNodeLabel": "VideoXLink-%sysId%",
				"nmosNodeDescription": "VideoXLink %sysId%",
				"nmosDeviceTxLabel": "%nodeLabel%/Sender/R%id%",
				"nmosDeviceTxDescription": "%nodeDes% Sender Device %name%",
				"nmosDeviceRxLabel": "%nodeLabel%/Receiver/S%id%",
				"nmosDeviceRxDescription": "%nodeDes% Receiver Device %name%",
				"nmosVideoTxLabel": "%nodeLabel%/Sender/R%id%-V",
				"nmosVideoTxDescription": "%nodeDes% Video Sender %name%",
				"nmosVideoRxLabel": "%nodeLabel%/Receiver/S%id%-V",
				"nmosVideoRxDescription": "%nodeDes% Video Receiver %name%",
				"nmosAudioTxLabel": "%nodeLabel%/Sender/R%id%-A",
				"nmosAudioTxDescription": "%nodeDes% Audio Sender %name%",
				"nmosAudioRxLabel": "%nodeLabel%/Receiver/S%id%-A",
				"nmosAudioRxDescription": "%nodeDes% Audio Receiver %name%",
				"ptp": true,
				"ptpLogAnnounceInterval": 1,
				"ptpSyncReceiptTimeout": 3,
				"ptpDomainNumber": 106,
				"ptpEth": "eth6",
				"ptpDscp": 46,
				"ptpPriority1": 128,
				"ptpPriority2": 127,
				"ptpAnnounceReceiptTimeout": 3,
				"ptpLogSyncInterval": -3,
				"ptpLogMinDelayReqInterval": -3,
				"ptpHybrid_e2e": false
			},
			"manIp": "0.0.0.0",
			"manIpSec": "0.0.0.0",
			"manPort": "0",
			"manAutCon": false,
			"enc": [
				{
				"id": "X8A8049-E1",
				"type": 1,
				"enabled": true,
				"name": "TX6 | LDX 2 | 16CH MAIN",
				"config": true,
				"running": true,
				"receiver": "X8A8322-D5",
				"rName": "DEC85-VK6 LDX2 |",
				"rSysName": "MER-XLINK-17"
				},
				{
				"id": "X8A8049-E2",
				"type": 1,
				"enabled": true,
				"name": "TX7 | LDX 4 | MAIN_BU",
				"config": true,
				"running": true,
				"receiver": "X8A0686-D1",
				"rName": "X8A0686-D1",
				"rSysName": ""
				},
				{
				"id": "X8A8049-E3",
				"type": 1,
				"enabled": true,
				"name": "TX8 | CHIP 2 | CAMsMON",
				"config": true,
				"running": true,
				"receiver": "X8A0686-D2",
				"rName": "X8A0686-D2",
				"rSysName": ""
				},
				{
				"id": "X8A8049-E4",
				"type": 1,
				"enabled": true,
				"name": "TX9 | VAR |",
				"config": true,
				"running": true,
				"receiver": "X8A0686-D3",
				"rName": "X8A0686-D3",
				"rSysName": ""
				},
				{
				"id": "X8A8049-E5",
				"type": 1,
				"enabled": true,
				"name": "RX10 AO2 | KDO2",
				"config": true,
				"running": true,
				"receiver": "X8A3800-D6",
				"rName": "X8A3800-D6",
				"rSysName": ""
				}
			],
			"dec": [
				{
				"id": "X8A8049-D1",
				"type": 2,
				"enabled": true,
				"name": "RX4 | GFX | R-PGM2",
				"config": true,
				"running": true,
				"sender": "X8A3800-E3",
				"sName": "X8A3800-E3",
				"sSysName": ""
				},
				{
				"id": "X8A8049-D2",
				"type": 2,
				"enabled": true,
				"name": "RX5 | ROUTE | BLANK",
				"config": true,
				"running": true,
				"sender": "X8A3800-E4",
				"sName": "X8A3800-E4",
				"sSysName": ""
				},
				{
				"id": "X8A8049-D3",
				"type": 2,
				"enabled": true,
				"name": "RX6 | AO2 | KDO_BU",
				"config": true,
				"running": true,
				"sender": "X8A3800-E6",
				"sName": "X8A3800-E6",
				"sSysName": ""
				}
			],
			"ndi": [],
			"srt": [],
			"ndifind": [],
			"l2s": [
				{
				"id": "X8A8049-L2S1",
				"type": 1,
				"name": "L2S1",
				"config": true,
				"cloudXlink": false,
				"localIp": "",
				"localPort": 0,
				"exIp": "",
				"exPort": 0,
				"running": false,
				"values": {
					"eth": "eth3",
					"master": false,
					"masterId": "none",
					"autoStart": false,
					"multicast": false,
					"rmcast": false,
					"encryption": true
				},
				"members": []
				}
			],
			"network": {
				"nets": [
				{
					"id": "eth0",
					"type": 1,
					"mac": "3C:EC:EF:BE:94:B0",
					"ip": "10.199.151.15",
					"gate": "10.199.151.1",
					"mask": "255.255.255.192",
					"ip_mask": "10.199.151.15/26",
					"dns1": "8.8.8.8",
					"dns2": "8.8.4.4",
					"dnsInUse1": "8.8.8.8",
					"dnsInUse2": "8.8.4.4",
					"dhcp": false,
					"link": true,
					"speed": "1Gbps",
					"system": true,
					"chipOK": true,
					"internet": true,
					"gatePing": true,
					"l2s": false,
					"l2sId": "none",
					"l2sName": "",
					"admin": true,
					"adminOnly": true,
					"igmp": false,
					"enabled": true,
					"defaultLan": false,
					"ndi": false,
					"default": false,
					"backup": false,
					"active": false,
					"allowed": true,
					"response": true,
					"wifiAllowed": false,
					"wifiConnect": false,
					"wifiConnected": false,
					"wifiFastRoaming": false,
					"wifiAp": false,
					"wifiApRunning": false,
					"wifiSSID": "",
					"wifiPSK": "",
					"wifiRSSI": 0,
					"linkTime": "2025-03-27 13:21:26 +0000"
				},
				{
					"id": "eth1",
					"type": 1,
					"mac": "3C:EC:EF:BE:94:B1",
					"ip": "0.0.0.0",
					"gate": "0.0.0.0",
					"mask": "0.0.0.0",
					"ip_mask": "0.0.0.0/0",
					"dns1": "0.0.0.0",
					"dns2": "0.0.0.0",
					"dnsInUse1": "0.0.0.0",
					"dnsInUse2": "0.0.0.0",
					"dhcp": true,
					"link": false,
					"speed": "?",
					"system": true,
					"chipOK": true,
					"internet": false,
					"gatePing": false,
					"l2s": false,
					"l2sId": "none",
					"l2sName": "",
					"admin": false,
					"adminOnly": false,
					"igmp": false,
					"enabled": false,
					"defaultLan": false,
					"ndi": false,
					"default": false,
					"backup": false,
					"active": false,
					"allowed": true,
					"response": true,
					"wifiAllowed": false,
					"wifiConnect": false,
					"wifiConnected": false,
					"wifiFastRoaming": false,
					"wifiAp": false,
					"wifiApRunning": false,
					"wifiSSID": "",
					"wifiPSK": "",
					"wifiRSSI": 0,
					"linkTime": ""
				},
				{
					"id": "eth2",
					"type": 1,
					"mac": "3C:EC:EF:BE:94:B2",
					"ip": "0.0.0.0",
					"gate": "0.0.0.0",
					"mask": "0.0.0.0",
					"ip_mask": "0.0.0.0/0",
					"dns1": "0.0.0.0",
					"dns2": "0.0.0.0",
					"dnsInUse1": "0.0.0.0",
					"dnsInUse2": "0.0.0.0",
					"dhcp": true,
					"link": false,
					"speed": "?",
					"system": true,
					"chipOK": true,
					"internet": false,
					"gatePing": false,
					"l2s": false,
					"l2sId": "none",
					"l2sName": "",
					"admin": false,
					"adminOnly": false,
					"igmp": false,
					"enabled": false,
					"defaultLan": false,
					"ndi": false,
					"default": false,
					"backup": false,
					"active": false,
					"allowed": true,
					"response": true,
					"wifiAllowed": false,
					"wifiConnect": false,
					"wifiConnected": false,
					"wifiFastRoaming": false,
					"wifiAp": false,
					"wifiApRunning": false,
					"wifiSSID": "",
					"wifiPSK": "",
					"wifiRSSI": 0,
					"linkTime": ""
				},
				{
					"id": "eth3",
					"type": 1,
					"mac": "3C:EC:EF:BE:94:B3",
					"ip": "0.0.0.0",
					"gate": "0.0.0.0",
					"mask": "0.0.0.0",
					"ip_mask": "0.0.0.0/0",
					"dns1": "0.0.0.0",
					"dns2": "0.0.0.0",
					"dnsInUse1": "0.0.0.0",
					"dnsInUse2": "0.0.0.0",
					"dhcp": false,
					"link": false,
					"speed": "?",
					"system": true,
					"chipOK": true,
					"internet": false,
					"gatePing": false,
					"l2s": true,
					"l2sId": "X8A8049-L2S1",
					"l2sName": "L2S1",
					"admin": false,
					"adminOnly": false,
					"igmp": false,
					"enabled": true,
					"defaultLan": false,
					"ndi": false,
					"default": false,
					"backup": false,
					"active": false,
					"allowed": true,
					"response": true,
					"wifiAllowed": false,
					"wifiConnect": false,
					"wifiConnected": false,
					"wifiFastRoaming": false,
					"wifiAp": false,
					"wifiApRunning": false,
					"wifiSSID": "",
					"wifiPSK": "",
					"wifiRSSI": 0,
					"linkTime": ""
				},
				{
					"id": "eth4",
					"type": 1,
					"mac": "3C:EC:EF:C0:2C:98",
					"ip": "10.35.1.252",
					"gate": "10.35.1.249",
					"mask": "255.255.255.248",
					"ip_mask": "10.35.1.252/29",
					"dns1": "0.0.0.0",
					"dns2": "0.0.0.0",
					"dnsInUse1": "8.8.8.8",
					"dnsInUse2": "8.8.4.4",
					"dhcp": true,
					"link": true,
					"speed": "10Gbps",
					"system": true,
					"chipOK": true,
					"internet": false,
					"gatePing": true,
					"l2s": false,
					"l2sId": "none",
					"l2sName": "",
					"admin": false,
					"adminOnly": false,
					"igmp": false,
					"enabled": true,
					"defaultLan": false,
					"ndi": false,
					"default": true,
					"backup": false,
					"active": true,
					"allowed": true,
					"response": true,
					"wifiAllowed": false,
					"wifiConnect": false,
					"wifiConnected": false,
					"wifiFastRoaming": false,
					"wifiAp": false,
					"wifiApRunning": false,
					"wifiSSID": "",
					"wifiPSK": "",
					"wifiRSSI": 0,
					"linkTime": "2025-03-27 13:21:09 +0000"
				},
				{
					"id": "eth5",
					"type": 1,
					"mac": "3C:EC:EF:C0:2C:99",
					"ip": "10.35.1.253",
					"gate": "10.35.1.249",
					"mask": "255.255.255.248",
					"ip_mask": "10.35.1.253/29",
					"dns1": "0.0.0.0",
					"dns2": "0.0.0.0",
					"dnsInUse1": "8.8.8.8",
					"dnsInUse2": "8.8.4.4",
					"dhcp": true,
					"link": true,
					"speed": "10Gbps",
					"system": true,
					"chipOK": true,
					"internet": false,
					"gatePing": true,
					"l2s": false,
					"l2sId": "none",
					"l2sName": "",
					"admin": false,
					"adminOnly": false,
					"igmp": false,
					"enabled": true,
					"defaultLan": false,
					"ndi": false,
					"default": false,
					"backup": true,
					"active": false,
					"allowed": true,
					"response": true,
					"wifiAllowed": false,
					"wifiConnect": false,
					"wifiConnected": false,
					"wifiFastRoaming": false,
					"wifiAp": false,
					"wifiApRunning": false,
					"wifiSSID": "",
					"wifiPSK": "",
					"wifiRSSI": 0,
					"linkTime": "2025-03-27 13:21:09 +0000"
				},
				{
					"id": "eth6",
					"type": 1,
					"mac": "08:C0:EB:8E:F0:6D",
					"ip": "10.199.183.15",
					"gate": "10.199.183.14",
					"mask": "255.255.255.254",
					"ip_mask": "10.199.183.15/31",
					"dns1": "8.8.8.8",
					"dns2": "8.8.4.4",
					"dnsInUse1": "8.8.8.8",
					"dnsInUse2": "8.8.4.4",
					"dhcp": false,
					"link": true,
					"speed": "25Gbps",
					"system": true,
					"chipOK": true,
					"internet": true,
					"gatePing": true,
					"l2s": false,
					"l2sId": "none",
					"l2sName": "",
					"admin": false,
					"adminOnly": false,
					"igmp": true,
					"enabled": true,
					"defaultLan": true,
					"ndi": false,
					"default": false,
					"backup": false,
					"active": false,
					"allowed": true,
					"response": true,
					"wifiAllowed": false,
					"wifiConnect": false,
					"wifiConnected": false,
					"wifiFastRoaming": false,
					"wifiAp": false,
					"wifiApRunning": false,
					"wifiSSID": "",
					"wifiPSK": "",
					"wifiRSSI": 0,
					"linkTime": "2025-03-27 13:21:19 +0000"
				},
				{
					"id": "eth7",
					"type": 1,
					"mac": "08:C0:EB:8E:F0:6C",
					"ip": "10.199.183.17",
					"gate": "10.199.183.16",
					"mask": "255.255.255.254",
					"ip_mask": "10.199.183.17/31",
					"dns1": "8.8.8.8",
					"dns2": "8.8.4.4",
					"dnsInUse1": "8.8.8.8",
					"dnsInUse2": "8.8.4.4",
					"dhcp": false,
					"link": true,
					"speed": "25Gbps",
					"system": true,
					"chipOK": true,
					"internet": true,
					"gatePing": true,
					"l2s": false,
					"l2sId": "none",
					"l2sName": "",
					"admin": false,
					"adminOnly": false,
					"igmp": true,
					"enabled": true,
					"defaultLan": false,
					"ndi": false,
					"default": false,
					"backup": false,
					"active": false,
					"allowed": true,
					"response": true,
					"wifiAllowed": false,
					"wifiConnect": false,
					"wifiConnected": false,
					"wifiFastRoaming": false,
					"wifiAp": false,
					"wifiApRunning": false,
					"wifiSSID": "",
					"wifiPSK": "",
					"wifiRSSI": 0,
					"linkTime": "2025-03-27 13:21:20 +0000"
				}
				],
				"ap": {},
				"modem": { "profiles": [], "simCards": [] }
			}
			}
		]
		}
	}
	}
`
